#!/bin/sh

MJC_ROOT=$(cd "$(dirname "$0")" && pwd)

if [ ! -f "$MJC_ROOT/mjc.jar" ]; then
    echo "mjc.jar not found, run 'ant' to build it!"
    exit 1
fi

java -cp "$MJC_ROOT/mjc.jar:$MJC_ROOT/lib/*" mjc.ARMMain $@
