#!/bin/bash
#
# This script submits the compressed source-only TAR archive to the TIGRIS
# submission system.
#
# Usage: ./submit [<recipient e-mail>]
#
# The default is to send it to submit@tigris.csc.kth.se.
#
# The script depends on the uuencode command from GNU sharutils and uses
# the mail command to send the mail.
#

MJC_DIR=$(dirname "$(cd "$(dirname "$0")" && pwd)")

if ! uuencode x < /dev/null > /dev/null 2>&1; then
    echo "Program uuencode missing. Please install GNU sharutils"
    exit 1
fi

if [ $# -ne 0 ] && [ $# -ne 1 ]; then
    echo "Usage: submit [<recipient e-mail>]"
    exit 1
fi

if [ ! -f $MJC_DIR/mjc.tar.gz ]; then
    echo "$MJC_DIR/mjc.tar.gz missing. Please run 'ant tar'"
    exit 1
fi

if [ $# -eq 1 ]; then
    TO=$1
else
    TO=submit@tigris.csc.kth.se
fi

echo "Submitting to $TO"

cat $MJC_DIR/mjc.tar.gz | uuencode x | mail -s "" $TO
